UniversityProject/Areas/Manager/Controllers/HomeManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace UniversityProject.Areas.Manager.Controllers
{
    public class HomeManagerController : Controller
    {
        // GET: Manager/HomeManager
        Models.db db = new Models.db();
        [Authorize(Roles = "3")] //Manager
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult RegisterMaster()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "3")] //Manager
        public ActionResult RegisterMaster([Bind(Include = "CodeMelly,FullName,Password,RePassword,IdRole")] Models.MyUser u1)
        {
            if (ModelState.IsValid)
            {
                if (db.myusers.Any(x => x.CodeMelly == u1.CodeMelly))
                {
                    var alert = "شما قبلا ثبت نام کردید";
                    return View(alert, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    u1.IdRole = 2;
                    db.myusers.Add(u1);
                    db.SaveChanges();
                }
                return View();
            }
            return View(u1);
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult AddLesson()
        {
            return View();
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult AddNewLesson(Models.Lesson l1)
        {
            db.Lessons.Add(l1);
            db.SaveChanges();
            return RedirectToAction("AddLesson");
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult MastersUniversity()
        {
            var q = from i in db.myusers where i.IdRole == 2 select i;
            var data = q.ToList();
            return View(data);
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult StudentsUniversity()
        {
            var q = from i in db.myusers where i.IdRole == 1 select i;
            var data = q.ToList();
            return View(data);
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult DeleteStudent(int id)
        {
            var q = from i in db.myusers where i.UserId == id select i;
            var data = q.Single();
            db.myusers.Remove(data);
            db.SaveChanges();
            return RedirectToAction("StudentsUniversity");
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult DeleteMaster(int id)
        {
            var q = from i in db.myusers where i.UserId == id select i;
            var data = q.Single();
            db.myusers.Remove(data);
            db.SaveChanges();
            return RedirectToAction("StudentsUniversity");
        }
        [Authorize(Roles = "3")] //Manager
        public ActionResult UpdateStudent(Models.MyUser u1)
        {
            if (db.myusers.Any(x => x.CodeMelly == u1.CodeMelly))
            {
                var alert = "کد ملی تکراری است";
                return View(alert, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var data = db.myusers.FirstOrDefault(t => t.UserId == u1.UserId);
                data.FullName = u1.FullName;
                data.Password = u1.Password;
                data.RePassword = u1.RePassword;
                data.CodeMelly = u1.CodeMelly;
                db.SaveChanges();
            }
            return View();
        }

    }
}

UniversityProject/Areas/Manager/Views/HomeManager/AddLesson.cshtml
@model UniversityProject.Models.Lesson

@{
    ViewBag.Title = "AddNewLesson";
}

<h2>AddNewLesson</h2>

@using (Html.BeginForm("AddNewLesson", "HomeManager", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lesson</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vahed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vahed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vahed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

UniversityProject/Areas/Manager/Views/HomeManager/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome Manager</h2>

UniversityProject/Areas/Manager/Views/HomeManager/MastersUniversity.cshtml
@model IEnumerable<UniversityProject.Models.MyUser>

@{
    ViewBag.Title = "MastersUniversity";
}

<h2>MastersUniversity</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CodeMelly)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RePassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdRole)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CodeMelly)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RePassword)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdRole)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
            @Html.ActionLink("Delete", "DeleteMaster", new { id=item.UserId })
        </td>
    </tr>
}

</table>

UniversityProject/Areas/Manager/Views/HomeManager/RegisterMaster.cshtml
@model UniversityProject.Models.MyUser

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ثبت نام | کنترل پنل</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link href="~/Content/MyFiles/dist/css/bootstrap-theme.css" rel="stylesheet" />
    <!-- Bootstrap rtl -->
    <link rel="stylesheet" href="~/Content/MyFiles/dist/css/rtl.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/MyFiles/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/MyFiles/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/MyFiles/dist/css/AdminLTE.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/MyFiles/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
@using (Html.BeginForm("RegisterMaster", "HomeManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <body class="hold-transition register-page">
        <div class="register-box">
            <div class="register-logo">
                <a href="#"><b>ثبت نام استاد</b></a>
            </div>

            <div class="register-box-body">
                <p class="login-box-msg">ثبت نام استاد جدید</p>

                <form>
                    <div class="form-group has-feedback">
                        <input type="text" class="form-control" placeholder="نام و نام خانوادگی" name="FullName">
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group has-feedback">
                        <input type="text" class="form-control" placeholder="کد ملی" name="CodeMelly">
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                        @Html.ValidationMessageFor(model => model.CodeMelly, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" placeholder="رمز عبور" name="Password">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" placeholder="تکرار رمز عبور" name="RePassword">
                        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                        @Html.ValidationMessageFor(model => model.RePassword, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="checkbox icheck">
                                <label>
                                    <input type="checkbox"> من <a href="#">قوانین و شرایط</a> را قبول میکنم.
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-12">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">ثبت نام</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <a href="https://localhost:44363/Home/Login" class="text-center">من قبلا ثبت نام کرده ام</a>
            </div>
            <!-- /.form-box -->
        </div>
        <!-- /.register-box -->
        <!-- jQuery 3 -->
        <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
        <script src="~/Content/MyFiles/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="~/Content/MyFiles/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- iCheck -->
        <script src="~/Content/MyFiles/plugins/iCheck/icheck.min.js"></script>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
    </body>
}
</html>

UniversityProject/Areas/Manager/Views/HomeManager/StudentsUniversity.cshtml
@model IEnumerable<UniversityProject.Models.MyUser>

@{
    ViewBag.Title = "StudentsUniversity";
}

<h2>StudentsUniversity</h2>

<table class="table" id="#StudentTbl">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodeMelly)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RePassword)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdRole)
        </th>
        <th>
            تغییرات
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodeMelly)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RePassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdRole)
            </td>
            <td>
                <button type="button" class="btn btn-info FillModalForEditStudent" id="FillModalForEditStudent" onclick="FillModalForEditStudent()" data-toggle="modal" data-target="#myModal">Edit</button>
                @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
                @Html.ActionLink("Delete", "DeleteStudent", new { id = item.UserId })
            </td>
        </tr>
    }

</table>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">ویرایش دانشجو</h4>
            </div>
            <div class="modal-body">
                <form action="/HomeManager/UpdateStudent" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1">نام و نام خانوادگی</label>
                        <input type="text" id="UserId " name="UserId" style="display:none;" />
                        <input type="text" class="form-control" id="FullName1" placeholder="نام و نام خانوادگی" name="FullName">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1"> کد ملی</label>
                        <input type="text" class="form-control" id="CodeMelly" placeholder=" کد ملی" name="CodeMelly">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">پسورد جدید"</label>
                        <input type="text" class="form-control" id="Password" placeholder="پسورد جدید" name="Password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">تکرار پسورد جدید</label>
                        <input type="text" class="form-control" id="RePassword" placeholder="تکرار پسورد جدید" name="RePassword">
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default">تایید</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".FillModalForEditStudent").click(function () {
                var currentrow = $(this).closest("tr");

                var UserId = currentrow.find("td:eq(0)").text();
                var CodeMelly = currentrow.find("td:eq(1)").text();
                var FullName = currentrow.find("td:eq(2)").text();
                var Password = currentrow.find("td:eq(3)").text();
                var RePassword = currentrow.find("td:eq(4)").text();

                $("#UserId").val(UserId);
                $("#CodeMelly").val(CodeMelly);
                $("#FullName1").val(FullName);
                $("#Password").val(Password);
                $("#RePassword").val(RePassword);
            });
        });

    </script>
    }